pull_request_rules:
  - name: Automatically merge dependencies
    conditions:
      - base=master
      - label=dependencies
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        strict: true
      delete_head_branch: {}
