name: Main
on: push
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - run: FILE=$(mktemp) && wget 'https://github.com/cogito-lang/libcogito/releases/download/v0.2.0/libcogito_0.2.0-1_amd64.deb' -qO $FILE && sudo dpkg -i $FILE && rm $FILE
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - run: python -m pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: python test/resource_test.py
